System check identified some issues:

WARNINGS:
company.Sellings.id_item: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
	HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.
company.Sellings.id_store: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
	HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.
Operations to perform:
  Apply all migrations: sessions, admin, company, auth, contenttypes, user
Running migrations:
  Rendering model states... DONE
  Applying company.0001_initial...Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/miki/django-trunk/django/core/management/__init__.py", line 330, in execute_from_command_line
    utility.execute()
  File "/home/miki/django-trunk/django/core/management/__init__.py", line 322, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/miki/django-trunk/django/core/management/base.py", line 347, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/miki/django-trunk/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/miki/django-trunk/django/core/management/commands/migrate.py", line 195, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/home/miki/django-trunk/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/home/miki/django-trunk/django/db/migrations/executor.py", line 147, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/miki/django-trunk/django/db/migrations/migration.py", line 118, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/miki/django-trunk/django/db/migrations/operations/models.py", line 59, in database_forwards
    schema_editor.create_model(model)
  File "/home/miki/django-trunk/django/db/backends/base/schema.py", line 284, in create_model
    self.execute(sql, params or None)
  File "/home/miki/django-trunk/django/db/backends/base/schema.py", line 110, in execute
    cursor.execute(sql, params)
  File "/home/miki/django-trunk/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/miki/django-trunk/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/miki/django-trunk/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/miki/django-trunk/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/home/miki/django-trunk/django/db/backends/sqlite3/base.py", line 316, in execute
    return Database.Cursor.execute(self, query)
django.db.utils.OperationalError: table "company_sellings" has more than one primary key

